sudo : required
services:
    - docker

before_install:
    - docker build -t corona -f Dockerfile.dev .

script:
    # - docker run corona npm run test -- --coverage
    - docker run -e CI=true corona npm run test
